/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package samplednd;

import javax.swing.JOptionPane;

/**
 *
 * @author Michael
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
public void executeMove(String producto, double presyo){
        Frame1 frm = new Frame1();
        
         try{
        String name = JOptionPane.showInputDialog(this, "Enter Quantity: (10 is the maximum)");
        int quant = Integer.parseInt(name);
        if(quant > 10){
            JOptionPane.showMessageDialog(this, "Invalid Quantity!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }else if(name.isEmpty() || name == ""){   
            JOptionPane.showMessageDialog(this, "Field is Empty!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }else{
            product.setText(""+producto);
            price.setText(""+presyo);
            quantity.setText(""+quant);
            double pr = Double.parseDouble(price.getText());
            double pay = pr * quant;
            payment.setText(""+pay);
        }
        }catch(NumberFormatException  e){
                JOptionPane.showMessageDialog(this, e);
        }catch(NullPointerException  e){
                JOptionPane.showMessageDialog(this, "Empty Input");
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        product = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        payment = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOTAL PAYMENT:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(400, 300, 270, 40);

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton1.setText("SPARKLE");
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 250, 160, 60);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton2.setText("COKE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 70, 160, 60);

        jButton3.setBackground(new java.awt.Color(0, 102, 51));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton3.setText("SPRITE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 130, 160, 60);

        jButton4.setBackground(new java.awt.Color(255, 102, 0));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton4.setText("FANTA");
        jPanel1.add(jButton4);
        jButton4.setBounds(30, 190, 160, 60);

        jButton5.setBackground(new java.awt.Color(0, 51, 204));
        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton5.setText("PEPSI");
        jPanel1.add(jButton5);
        jButton5.setBounds(30, 250, 160, 60);

        jButton6.setBackground(new java.awt.Color(0, 153, 51));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton6.setText("7 UP");
        jPanel1.add(jButton6);
        jButton6.setBounds(190, 130, 160, 60);

        jButton7.setBackground(new java.awt.Color(51, 153, 255));
        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton7.setText("SUMMIT");
        jPanel1.add(jButton7);
        jButton7.setBounds(190, 190, 160, 60);

        jButton8.setBackground(new java.awt.Color(255, 102, 102));
        jButton8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton8.setText("JAZZ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(190, 70, 160, 60);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\t      PRICE LIST:\n     COKE    php12.00       JAZZ        php8.00\n     SPRITE    php11.00       7UP         php9.00\n     FANTA   php11.00       SUMMIT   php10.00\n     PEPSI     php12.00       SPARKLE  php8.00");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 330, 320, 110);

        product.setBackground(new java.awt.Color(51, 51, 51));
        product.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        product.setForeground(new java.awt.Color(0, 204, 0));
        product.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(product);
        product.setBounds(400, 70, 270, 50);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELECT PRODUCT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 20, 320, 40);

        price.setBackground(new java.awt.Color(51, 51, 51));
        price.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        price.setForeground(new java.awt.Color(0, 204, 0));
        price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(price);
        price.setBounds(400, 160, 270, 50);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SELECTED QUANTITY:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 210, 270, 40);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SELECTED PRODUCT:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 30, 270, 40);

        quantity.setBackground(new java.awt.Color(51, 51, 51));
        quantity.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        quantity.setForeground(new java.awt.Color(0, 204, 0));
        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(quantity);
        quantity.setBounds(400, 250, 270, 50);

        payment.setBackground(new java.awt.Color(51, 51, 51));
        payment.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        payment.setForeground(new java.awt.Color(0, 204, 0));
        payment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(payment);
        payment.setBounds(400, 340, 270, 50);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRICE:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 120, 270, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        executeMove("COKE", 12.00);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       executeMove("JAZZ", 08.00);
   
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       executeMove("SPRITE", 11.00);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField payment;
    public static javax.swing.JTextField price;
    public static javax.swing.JTextField product;
    public static javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
